#!/usr/bin/env node

const { program } = require('commander');
const inquirer = require('inquirer');
const chalk = require('chalk');


// 为什么网上的傻x文章永远跑不起来呢？高你妈啊
program
  .command('init')
  .alias('i')
  .description('init the project')
  .action(option => {
    let config = {
      projectName: null
    };

    console.log(chalk.blue('hello v1.0.0'));
    
    let promps = [];
    // if (config.projectName === null) {
      promps.push({
        type: 'input',
        name: 'projectName',
        message: 'please input the name of your project',
        validate: input => {
          if (!input) {
            return '项目名称不能为空';
          }
          // 更新对象中属性的数据
          config.projectName = input;
          return true;
        }
      });
    // }
    
    inquirer.prompt(promps).then(async (answers) => {
      // do something here
      console.log(answers);
    });
  });

  program.parse(process.argv);